CRITICAL - 2021-03-29 02:21:45 --> Use of undefined constant form - assumed 'form' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 02:21:52 --> Use of undefined constant form - assumed 'form' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 02:22:12 --> Use of undefined constant form - assumed 'form' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 06:26:01 --> Class 'App\Model\User' not found
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->register()
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-29 07:13:57 --> Argument 1 passed to CodeIgniter\Router\RouteCollection::get() must be of the type string, array given, called in C:\xampp\htdocs\ci4-auth\app\Config\Routes.php on line 39
#0 C:\xampp\htdocs\ci4-auth\app\Config\Routes.php(39): CodeIgniter\Router\RouteCollection->get(Array, '/login', 'Auth::login')
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(803): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 07:13:59 --> Argument 1 passed to CodeIgniter\Router\RouteCollection::get() must be of the type string, array given, called in C:\xampp\htdocs\ci4-auth\app\Config\Routes.php on line 39
#0 C:\xampp\htdocs\ci4-auth\app\Config\Routes.php(39): CodeIgniter\Router\RouteCollection->get(Array, '/login', 'Auth::login')
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(803): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 07:14:09 --> Argument 1 passed to CodeIgniter\Router\RouteCollection::get() must be of the type string, array given, called in C:\xampp\htdocs\ci4-auth\app\Config\Routes.php on line 39
#0 C:\xampp\htdocs\ci4-auth\app\Config\Routes.php(39): CodeIgniter\Router\RouteCollection->get(Array, '/login', 'Auth::login')
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(803): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 07:31:21 --> Undefined index: email
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(87): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 87, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 07:31:46 --> Undefined index: email
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(87): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 87, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 07:33:39 --> Use of undefined constant user - assumed 'user' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\ci4-auth\app\Controllers\Auth.php(98): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-29 08:35:29 --> Undefined variable: session
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(7): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 7, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 08:37:13 --> Undefined variable: config
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(7): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 7, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 08:40:30 --> Array to string conversion
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(8): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 8, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 08:41:02 --> Array to string conversion
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(8): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 8, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 08:41:04 --> Array to string conversion
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(8): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 8, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:28:08 --> Object of class CodeIgniter\Session\Session could not be converted to string
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#3 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#4 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-03-29 10:32:25 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(63): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#5 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-29 10:33:20 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(63): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#5 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-29 10:33:29 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(63): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#5 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-29 10:41:31 --> Use of undefined constant base_url - assumed 'base_url' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:44:20 --> Call to undefined method CodeIgniter\Session\Session::userdata()
#0 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include()
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#3 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#4 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-03-29 10:45:57 --> Undefined property: CodeIgniter\View\View::$load
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(7): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 7, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:47:05 --> Undefined property: CodeIgniter\View\View::$load
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:50:40 --> Array to string conversion
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(23): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 23, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:18 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:33 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:34 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:38 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:58 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:53:59 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:54:00 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(10): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 10, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(20): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-29 10:57:46 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\ci4-auth\app\Views\profile.php(24): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 24, Array)
#1 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('profile', Array, true)
#4 C:\xampp\htdocs\ci4-auth\app\Controllers\Home.php(22): view('profile', Array)
#5 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\Home->profile()
#6 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\ci4-auth\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4-auth\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
